### ISSUE TITLE
Explain how the statistics are created

### ISSUE THREAD

**Issue by ynux** [EqualStreetNames/equalstreetnames#150] opened 2021-03-24 10:44 UTC
Please add some explanation about how the statistics are generated by `statistics.php`. In  the `docs/scripts/README.md` there's a link to a documentation `statistics.md` that does not exist.

**Comment by jbelien** [comment] 2021-03-26 07:58
Duplicate of #27

**Closed by jbelien** 2021-03-26 07:58 UTC
Labels: documentation
