### ISSUE TITLE
Boundary overwriting URL parameters

### ISSUE THREAD

**Issue by RobinLinde** [EqualStreetNames/equalstreetnames#160] opened 2021-03-30 21:23 UTC
When opening a direct link with location parameters in the URL, like `https://assen.equalstreetnames.eu/nl/index.html#18.05/52.995805/6.569603`, the page automatically fits the bounds using the boundary.
```typescript
map.fitBounds(boundingBox as LngLatBoundsLike, { padding: 25 });
```
I guess it would probably be a good idea to check whether a location is included in the URL, and only run fitBounds if no parameters, or empty parameters are specified.

@jbelien Also just noticed this if my first issue 😃

**Comment by jbelien** [comment] 2021-04-10 07:26
That will be automatically fixed in every website at next (automated) deployment.

**Comment by jbelien** [comment] 2021-04-11 08:50
This is still not fixed...

There is definitely a conflict between `bounds` (or `fitBounds()`) and the parameters from the hash (https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/map.js#L447-L462)

**Comment by jbelien** [comment] 2021-04-11 10:12
The issue is **fixed** when using `app.center` + `app.zoom` in 3aae34a57c92c44ab7e51b2f20771276bb140362.

---

The issue is **not fixed** when using `app.bbox`.
The issue is **not fixed** when `app.center`, `app.zoom`, and `app.bbox` are not defined (the app uses bounds from `boundary.geojson` in that case).
Reason: https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/map.js#L458-L461

---

[Mapbox geo-viewport](https://github.com/mapbox/geo-viewport) (converting bounds to zoom level + center) seemed to be a solution but won't work since we need the map size which is only available after page load.

**Comment by jbelien** [comment] 2021-04-11 10:31
Well ... That IS fun(ny) ...

I commited 8a92b0c327eb06ca0699d24c915d63a345cd8d9c for consistency with previous commit and ... it seemed to have fix this issue.

I've deployed the update on https://equalstreetnames.brussels/ and it seems to works as expected.
I'll wait for deployment on all websites to close this issue.

**Comment by jbelien** [comment] 2021-04-15 05:56
It seems to be fixed ! 🎉

**Closed by jbelien** 2021-04-15 05:56 UTC
Labels: bug
